codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        threshold: 5
    patch:
      default:
        threshold: 5
    changes: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no
