[package]
name = "ray_tracing"
version = "0.1.0"
authors = ["LachezarLechev <lachezar.lechev@skydreams.com>"]
edition = "2018"

[lib]
name = "ray_tracing"
path = "src/lib.rs"

[[bin]]
name = "ray_tracing"
path = "src/main.rs"

[dependencies]
